- name: bug
  description: Something isn't working
  color: d73a4a
- name: documentation
  description: Improvements or additions to documentation
  color: 0075ca
- name: Migration
  description: We are migrating the database
  color: cfd3d7
