- name: bug
  description: Something isn't working
  color: d73a4a
- name: documentation
  description: Additions to documentation
  color: 0075ca
- name: Enhancement
  description: We are making cool changes
  color: cfd3d7
- name: Hack
  description: We are hacking a fix
  color: f0971f
