def hello():
    '''Says hello'''
    print("Hello")
    print("Hello")
    print("Hello")
    print("Hello")
    print("Hello")
    print("Hello")
    print("Hello")
    print("Hello")
    print("Hello")
    print("Hello")
    print("Hello")
    print("Hello")
    print("Hello")
    print("Hello")
    print("Hello")
    print("Hello")
