name: build_image

on:
  issue_comment:
    types: [created]

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    if: ${{ github.event.comment.body == 'staging' }}
    uses: actions/checkout@v2
    with:
      ref: "refs/pull/${{ github.event.issue.number }}/merge"

  - name: $github
    run:   echo "$ISSUE_NUMBER"
    env:
     GITHUB_CONTEXT: ${{ toJson(github) }}
     ISSUE_NUMBER: ${{ github.event.issue.number }}

  - name: build image
    if: ${{ github.event.comment.body == 'staging' }}
    uses: docker/build-push-action@v2
    with:
      context: .
      file: ./Dockerfile
      push: false
      build-args: |
        TEST_ARG=booya
        ANOTHER=boom
      tags: |
        892770019132.dkr.ecr.us-east-1.amazonaws.com/actions-testing:latest
        892770019132.dkr.ecr.us-east-1.amazonaws.com/actions-testing:${{ github.sha }}
