name: build_image

on:
  issue_comment:
    types: [created]

jobs:
 dump:
  runs-on: ubuntu-latest
  steps:
  - name: $github
    if: github.event.comment.body == "staging"
    run:   echo "$GITHUB_CONTEXT"
    env:
     GITHUB_CONTEXT: ${{ toJson(github) }}
