name: build_image

on:
  issue_comment:
    types: [created]

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v2

  - name: $github
    run:   echo "$GITHUB_CONTEXT"
    env:
     GITHUB_CONTEXT: ${{ toJson(github) }}

  - name: build image
    if: ${{ github.event.comment.body == 'staging' }}
    uses: docker/build-push-action@v2
    with:
      context: .
      file: ./Dockerfile
      push: false
      build_args: |
        TEST_ARG=booya
        ANOTHER=boom
