name: build_image

on:
  issue_comment:
    types: [created]

jobs:
 dump:
  runs-on: ubuntu-latest
  steps:
  - name: $github
    run:   echo "$GITHUB_CONTEXT"
    env:
     GITHUB_CONTEXT: ${{ toJson(github) }}
  - name: test if
    if: ${{ github.event.comment.body == 'staging' }}
    run: echo "OH YEAH!"
