name: Tear Down Miniflow

on:
  push:
    branches:
      - master

jobs:
  tear_down:
    name: Tear Down the App
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Take Down App
      run: |
        aws ecs update-service --cluster integration-ecs --service actions-testing-${{ github.actor }} --desired-count 0
