name: Say Hello

on:
  push:
    branches:
      - master

jobs:
  hello:
    name: Hello
    runs-on: ubuntu-latest

    steps:
    # - name: $github
    #   run: |
    #     echo "$GITHUB_CONTEXT"
    #     echo "$FIRST_COMMITTER"
    #   env:
    #    GITHUB_CONTEXT: ${{ toJson(github) }}
    #    ISSUE_NUMBER: ${{ github.event.issue.number }}
    #    FIRST_COMMITTER: ${{ github['event']['commits'][0]['author']['username'] }}

    - name: Say Hello to Me
      uses: jwanderson1326/my-first-action@v3
      with:
        who-to-greet: "JUSTIN!!!"
